#!/bin/sh

set -eu

(
    echo 'strict digraph states {'
    sed -r -n 's/^[\t ]*\(([a-z_]+)[\t ]*,[\t ]*"([A-Za-z_]*)"[\t ]*,[ ]*([a-z_]+)[\t ]*\)[\t ]*,.*$/\1 -> \3 [label="\2"];/p'
    echo '}'
) | dot -Txlib
