#!/usr/bin/env python3

import bottisota.bus

botconn = bottisota.bus.BotConnection()

botconn.sys_clk()
botconn.sys_drv(20, 270)
while True:
    x, y, speed, heading = botconn.sys_pos()
    if speed == 0:
        botconn.sys_drv(20, (heading + 90) % 360)

botconn.disconnect()
